package gogopls

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestSyncerSyncAndCleanup(t *testing.T) {
	root := t.TempDir()
	srcPath := filepath.Join(root, "main.gogo")

	writeFile(t, srcPath, strings.TrimSpace(`
package main

type Number = int | float64
`))

	syncer := NewSyncer(root)
	if err := syncer.Sync(); err != nil {
		t.Fatalf("Sync() error = %v", err)
	}

	genPath := filepath.Join(root, "main_gogo_gen.go")
	got := readFile(t, genPath)
	if !strings.Contains(got, "// Code generated by gogo; DO NOT EDIT.") {
		t.Fatalf("generated file missing header:\n%s", got)
	}
	if !strings.Contains(got, "type Number interface{ int | float64 }") {
		t.Fatalf("generated file missing transformed union:\n%s", got)
	}

	writeFile(t, srcPath, strings.TrimSpace(`
package main

type Color enum {
	Red
	Green
}
`))
	if err := syncer.Sync(); err != nil {
		t.Fatalf("Sync() after update error = %v", err)
	}

	got = readFile(t, genPath)
	if !strings.Contains(got, "type Color int") {
		t.Fatalf("generated file missing updated enum:\n%s", got)
	}

	if err := os.Remove(srcPath); err != nil {
		t.Fatalf("Remove(%s) error = %v", srcPath, err)
	}
	if err := syncer.Sync(); err != nil {
		t.Fatalf("Sync() after delete error = %v", err)
	}
	if _, err := os.Stat(genPath); !os.IsNotExist(err) {
		t.Fatalf("expected generated file to be removed, stat err = %v", err)
	}

	writeFile(t, srcPath, "package main\n")
	if err := syncer.Sync(); err != nil {
		t.Fatalf("Sync() before cleanup error = %v", err)
	}
	if err := syncer.Cleanup(); err != nil {
		t.Fatalf("Cleanup() error = %v", err)
	}
	if _, err := os.Stat(genPath); !os.IsNotExist(err) {
		t.Fatalf("expected cleanup to remove generated file, stat err = %v", err)
	}
}

func TestSyncerRecreatesGeneratedFileWhenMissingOrModified(t *testing.T) {
	root := t.TempDir()
	srcPath := filepath.Join(root, "main.gogo")
	genPath := filepath.Join(root, "main_gogo_gen.go")

	writeFile(t, srcPath, `
package main

type Number = int | float64
`)

	syncer := NewSyncer(root)
	if err := syncer.Sync(); err != nil {
		t.Fatalf("Sync() error = %v", err)
	}

	if err := os.Remove(genPath); err != nil {
		t.Fatalf("Remove(%s) error = %v", genPath, err)
	}
	if err := syncer.Sync(); err != nil {
		t.Fatalf("Sync() after generated delete error = %v", err)
	}
	got := readFile(t, genPath)
	if !strings.Contains(got, "type Number interface{ int | float64 }") {
		t.Fatalf("generated file was not recreated:\n%s", got)
	}

	writeFile(t, genPath, "package main\n\nvar stale = true\n")
	if err := syncer.Sync(); err != nil {
		t.Fatalf("Sync() after generated modification error = %v", err)
	}
	got = readFile(t, genPath)
	if strings.Contains(got, "var stale = true") {
		t.Fatalf("generated file was not restored:\n%s", got)
	}
}

func TestSyncerRemovesOrphanedGeneratedFiles(t *testing.T) {
	root := t.TempDir()
	orphanPath := filepath.Join(root, "orphan_gogo_gen.go")
	writeFile(t, orphanPath, "package main\n")

	syncer := NewSyncer(root)
	if err := syncer.Sync(); err != nil {
		t.Fatalf("Sync() error = %v", err)
	}

	if _, err := os.Stat(orphanPath); err == nil || !os.IsNotExist(err) {
		t.Fatalf("expected orphaned generated file to be removed, stat err = %v", err)
	}
}

func writeFile(t *testing.T, path, contents string) {
	t.Helper()
	if err := os.WriteFile(path, []byte(contents), 0o644); err != nil {
		t.Fatalf("WriteFile(%s) error = %v", path, err)
	}
}

func readFile(t *testing.T, path string) string {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile(%s) error = %v", path, err)
	}
	return string(data)
}
