package sourcegen

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/benbenbenbenbenben/gogo/internal/preprocessor"
)

const (
	SourceExt       = ".gogo"
	GeneratedSuffix = "_gogo_gen.go"
	GeneratedHeader = "// Code generated by gogo; DO NOT EDIT.\n\n"
)

func GeneratedPath(srcPath string) string {
	return strings.TrimSuffix(srcPath, SourceExt) + GeneratedSuffix
}

func WritePreprocessedToDir(srcPath, outDir string) (string, error) {
	raw, err := os.ReadFile(srcPath)
	if err != nil {
		return "", fmt.Errorf("read %s: %w", srcPath, err)
	}

	out := preprocessor.Process(string(raw))
	base := filepath.Base(srcPath)
	goName := strings.TrimSuffix(base, SourceExt) + ".go"
	outPath := filepath.Join(outDir, goName)

	if err := os.WriteFile(outPath, []byte(out), 0o644); err != nil {
		return "", fmt.Errorf("write %s: %w", outPath, err)
	}

	return outPath, nil
}

func WriteGeneratedSibling(srcPath string) (string, error) {
	raw, err := os.ReadFile(srcPath)
	if err != nil {
		return "", fmt.Errorf("read %s: %w", srcPath, err)
	}

	out := preprocessor.Process(string(raw))
	genPath := GeneratedPath(srcPath)
	if err := os.WriteFile(genPath, []byte(GeneratedHeader+out), 0o644); err != nil {
		return "", fmt.Errorf("write %s: %w", genPath, err)
	}

	return genPath, nil
}

func RemoveGeneratedSibling(srcPath string) error {
	err := os.Remove(GeneratedPath(srcPath))
	if errors.Is(err, os.ErrNotExist) {
		return nil
	}
	return err
}
